{"uuid": "fd3ac5a1-81d9-4a93-ab7a-445614c4656e", "children": ["6ab1cfa7-3616-4fcd-8a70-b76b0fc982f6"], "befores": [{"name": "driver", "status": "passed", "start": 1736905040973, "stop": 1736905041700}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=57360): Max retries exceeded with url: /session/9530aa3cab790942929dd8710ec8fef4/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105129c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/conftest.py\", line 54, in driver\n    attach = driver.get_screenshot_as_png()\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 306, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 326, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/Users/timofeitimko/PycharmProjects/automation_qa_art/.venv/lib/python3.12/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1736905123180, "stop": 1736905123189}], "start": 1736905040973, "stop": 1736905123189}